name: Build Development Build
on:
    push:
        branches: ["dev"]
    workflow_dispatch:

jobs:
    build:
        name: Build Signed APK
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                token: ${{ secrets.GH_PAT }}
                submodules: true

            - name: Validate Gradle Wrapper
              uses: gradle/wrapper-validation-action@v1

            - name: Setup GraalVM
              uses: graalvm/setup-graalvm@v1
              with:
                github-token: ${{ secrets.GH_PAT }}
                java-version: 19
                version: latest
                cache: 'gradle'

            - name: Build Debug APK
              run: ./gradlew :app:assembleDebug
              env:
                KSF_NAME: ${{ secrets.F }}
                KSF_PASS: ${{ secrets.P }}
                KEY_NAME: ${{ secrets.A }}
                KEY_PASS: ${{ secrets.K }}

            - name: Upload APK (Development)
              if: github.ref_name == 'dev'
              uses: actions/upload-artifact@v4
              with:
                name: Release
                path: app/build/outputs/apk/debug/app-debug.apk

